### ISSUE TITLE
updateIdentities not available in react

### ISSUE THREAD

**Issue by mdonke** [adobe/aepsdk-react-native#101]
Hello,

is there any plan or even ETA to expose all methods of `com.adobe.marketing.mobile.edge.identity.Identity` to be used in react native?

Namely 
```
updateIdentities
removeIdentity
getIdentities
```

Thank you!

**Comment by emdobrin** [comment]
Hello @mdonke, 

Glad you are asking. Yes, please keep an eye on the upcoming release, we are working on including those APIs the aepedgeidentity package soon.

Thanks,
Emilia Dobrin

**Comment by mdonke** [comment]
working fine! Thank you!
