### ISSUE TITLE
Make push message tracking functions available in React Native

### ISSUE THREAD

**Issue by magcode** [adobe/aepsdk-react-native#123]
Hello,

it would be benefitial if the API listed [here](https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/blob/master/using-mobile-extensions/adobe-journey-optimizer/api-reference.md) would be available in React Native without the need to use custom NativeModules.

Thank you

**Comment by shtomar-adb** [comment]
Hi @magcode, 

As of now there is no plan to expose Push tracking functions in JS. This is because the call backs functions for push message receive are present in native side.

**Comment by magcode** [comment]
Thanks @shtomar-adb 

> the call backs functions for push message receive are present in native side

I actually don't need any native code for receiving Push messages from AJO. All can be done in react native/JS code. Thus I was wondering. Anyway. I understood that this is not considered and will implement it using NativeModules.
