### ISSUE TITLE
MobileCore.resetIdentities() leads to TWO ECIDs in edgeidentity

### ISSUE THREAD

**Issue by mdonke** [adobe/aepsdk-react-native#172]
Hello, when I try to reset the ECID using `MobileCore.resetIdentities();` something strange happens:

Log output when calling "MobileCore.resetIdentities();"

```
04-11 17:58:34.428   978  1150 D AdobeExperienceSDK: IdentityExtension - generateURLEncodedValuesCustomerIdString : No Visitor ID exists in the provided list to generate for URL.
04-11 17:58:34.428   978  1150 D AdobeExperienceSDK: IdentityHitsDatabase - updatePrivacyStatus : Privacy Status was opted-in, so attempting to send all the queued Identity hits from database.
04-11 17:58:34.442   978  1150 D AdobeExperienceSDK: IdentityHitsDatabase - IdentityHitsDatabase.queue : Queued an identity sync call with URL: (https://dpm.demdex.net/id?d_ver=2&d_rtbd=json&d_orgid=XXX%40AdobeOrg&d_mid=18594564454102280516426503658680704367) resulted from the event: (6dc3c852-448f-4157-81e9-b3431b305bfc).
04-11 17:58:34.445   978  1151 D AdobeExperienceSDK: EdgeIdentity - IdentityState - Identity direct ECID updated to '18594564454102280516426503658680704367', updating the IdentityMap
04-11 17:58:34.450   978  2581 D AdobeExperienceSDK: IdentityExtension - IdentityHitsDatabase.process : Sending request: (https://dpm.demdex.net/id?d_ver=2&d_rtbd=json&d_orgid=XXX%40AdobeOrg&d_mid=18594564454102280516426503658680704367).
04-11 17:58:34.450   978  1150 D AdobeExperienceSDK: IdentityExtension - handleIdentityRequestReset: Did reset identifiers and queued force sync event.
04-11 17:58:34.451   978  2584 D AdobeExperienceSDK: HttpConnectionHandler - Connecting to URL https://dpm.demdex.net/id?d_ver=2&d_rtbd=json&d_orgid=XXX%40AdobeOrg&d_mid=18594564454102280516426503658680704367 (GET)
04-11 17:58:34.684   978  2581 D AdobeExperienceSDK: IdentityExtension - handleNetworkResponseMap : ECID Service returned (mid: 18594564454102280516426503658680704367, blob: j8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI, hint: 6, ttl: 604800).
```

When I now click "EDGEIDENTITY/GETIDENTIES" button in the app the following is printed/returned:

```
04-11 18:00:03.971   978  1232 I ReactNativeJS: AdobeExperienceSDK: Identity.getIdentities {"identityMap":{"ECID":[{"id":"08827957854277672686629948177970628054","authenticatedState":"ambiguous","primary":false},{"id":"18594564454102280516426503658680704367","authenticatedState":"ambiguous","primary":false}]}}
```

As you can see getIdentities now has TWO ECIDs which will be transmitted when calling "Edge.sendEvent".
How can this be fixed?

Testcode:
https://github.com/mdonke/aepsdk-react-native/commit/4675f0386e26dcee29f283c6736e8a391fddc1d8

**Comment by cacheung** [comment]
Hi @mdonke,
     If you registered both identity extension (AEPMobileIdentity.class on iOS as an example) and EdgeIdentity extension (AEPMobileEdgeIdentity.class) in the app, this is the expected behavior.  
     Please see the[ FAQ ](https://aep-sdks.gitbook.io/docs/foundation-extensions/identity-for-edge-network/identity-faq)and [ResetIdentity](https://aep-sdks.gitbook.io/docs/foundation-extensions/identity-for-edge-network/api-reference#resetidentities) documentation for more info.
     
     Do you need identity extension in your app?  Can you tell us about your resetIdentity use case?

Best Regards,
Calise

**Comment by magcode** [comment]
Hi Calise,

thanks for the hint. I actually don't need the identity extension. I removed it and its working fine now.
Possibly I got confused by the message in Tags that "Identity" is a requirement for "Adobe Experience Platform Edge Network".

![image](https://user-images.githubusercontent.com/9279656/163126406-64429430-9326-4fc2-a923-ff608447a9bb.png)

**Comment by mdonke** [comment]
Hi Calise,

thanks for the hint. I actually don't need the identity extension. I removed it and its working fine now.
Possibly I got confused by the message in Tags that "Identity" is a requirement for "Adobe Experience Platform Edge Network".

![image](https://user-images.githubusercontent.com/60607190/163126744-0dfabda4-5fa8-4d5a-8ae8-5e1586851d65.png)

**Comment by mdonke** [comment]
Thank you Emilia, this is exactly how I set it up now.
