### ISSUE TITLE
Issue with building for ios framework 13.0

### ISSUE THREAD

**Issue by 1237889321** [adobe/aepsdk-react-native#262]
Kindly refer to the changes needed for supporting latest iOS build processes using cocoapods frameworks:

https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

Thanks,
Rohit Garg

**Comment by cdhoffmann** [comment]
@1237889321 Hey there, can you use the issue template to provide more information on what the issue you're seeing is please?

**Comment by cacheung** [comment]
@1237889321 Can you provide more details about your request?

**Comment by ayoubechc** [comment]
@1237889321  did you find any solution, I have the same issue here , can not build iOS when setting platform :ios, '13.0' in pod file @cdhoffmann @cacheung

**Comment by cacheung** [comment]
@ayoubechc What error do you see in the log on iOS platform. e.g Xcode logs? What Xcode version you are using?

**Comment by cacheung** [comment]
We have released aep-react-native [version 5.x](https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/#react-native).  Do you still reproduce the issue?  If so, please provide reproducible steps and native iOS log.
