### ISSUE TITLE
React Native iOS - Underlying Objective-C module 'AEPRulesEngine' not found

### ISSUE THREAD

**Issue by snanthagopal** [adobe/aepsdk-react-native#263]
The latest version "@adobe/react-native-aepcore": "2.0.0" experiencing this issue in iOS only and it was working 1.0.0 

#### Steps to Reproduce
1. yarn add @adobe/react-native-aepcore
2. cd iOS && pod install
3. Import these on your iOS AppDelegate
    import AEPCore
    import AEPSignal
    import AEPServices
    import AEPLifecycle
4. Go to product from the menu --> Archive

#### Platform and Version
React Native - iOS

#### Logs taken while reproducing problem
![AEPCoreEngine](https://user-images.githubusercontent.com/2344753/230054075-a10d3da8-c97d-4572-b798-9f66d345463b.png)

<img width="1452" alt="Screenshot 2023-04-05 at 11 04 14" src="https://user-images.githubusercontent.com/2344753/230054719-3b5449db-ff08-4510-8bbf-ec3a4cc357a3.png">

**Comment by csnvrl** [comment]
We're having the same issue

**Comment by dsoffiantini** [comment]
Hi @snanthagopal, we are tracking issues with adobe sdks and the latest version of xcode (14.3). We are currently testing some workarounds until we hear back from Apple on how to solve the underlying issue. For now, downgrading xcode will solve the issue. I'll keep this thread up to date with any new updates we get back from Apple.

**Comment by praveek** [comment]
We are still working on the underlying issue but in the meantime you can use one of these workarounds
1) Linking as static frameworks by adding`use_frameworks! :linkage => :static` to your Podfile. Flipper does not work when `use_frameworks` is enabled, and you should remove it from Podfile. 

2) Adding the `-no-verify-emitted-module-interface` flag to failing targets to avoid verification failure.
You can add the following post install hook to your Podfile to automatically add this flag to AEP library targets. 
```
post_install do |installer|
  installer.pods_project.targets.each do |t|
    if t.name.start_with?("AEP")
      t.build_configurations.each do |bc|
          bc.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -no-verify-emitted-module-interface'
      end
    end
  end
end
```

**Comment by gevgasparyan** [comment]
Same issue after upgrading to xCode 14.3.

Adding these lines solved the issue

```
installer.pods_project.targets.each do |t|
    if t.name.start_with?("AEP")
      t.build_configurations.each do |bc|
          bc.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -no-verify-emitted-module-interface'
      end
    end
  end
```

**Comment by ram-vilash** [comment]
Nothing seems to be working, I am still getting the same issue. 

XCode Version - 14.3.1,
RN - 0.69.1

**Comment by cacheung** [comment]
@ram-vilash this issue is still open, the workaround is having these lines in the Podfile.  Have you tried that?

```
post_install do |installer|
  installer.pods_project.targets.each do |t|
    if t.name.start_with?("AEP")
      t.build_configurations.each do |bc|
          bc.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -no-verify-emitted-module-interface'
      end
    end
  end
end
```

**Comment by cacheung** [comment]
@ram-vilash, have you tried with the workaround and does it work for you?  We are planning to close this issue soon since this is not a Adobe SDK issue.
