### ISSUE TITLE
Broken Android build:  Non-pinned native packages result in dependency which is not yet published

### ISSUE THREAD

**Issue by kevindice** [adobe/aepsdk-react-native#267]
### Expected Behaviour

My Android app continues to build because I have not changed any Adobe dependencies since May 16.

### Actual Behaviour

The packages in this repository reference broad ranges of the underlying Android native code packages resulting in non-consensual upgrades, exposing my team's project to risk through non-deterministic builds.  At least one of the native code packages is specifically requiring `com.adobe.marketing.mobile:core:2.2.0` which has not been published yet, so our Android build has begun to fail.

This is a critical blocker.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.adobe.marketing.mobile:core:2.2.0.
     Required by:
         project :app > project :adobe_react-native-aepcore
   > Could not find com.adobe.marketing.mobile:core:2.2.0.
     Required by:
         project :app > com.adobe.marketing.mobile:assurance:2.1.0
         project :app > com.adobe.marketing.mobile:signal:2.0.1
         project :app > com.adobe.marketing.mobile:target:2.0.0
   > Could not find com.adobe.marketing.mobile:core:2.2.0.
     Required by:
         project :app > com.adobe.marketing.mobile:identity:2.0.2
   > Could not find com.adobe.marketing.mobile:core:2.2.0.
     Required by:
         project :app > com.adobe.marketing.mobile:lifecycle:2.0.2-SNAPSHOT:20230427.221352-1
   > Could not find com.adobe.marketing.mobile:core:2.2.0.
     Required by:
         project :app > com.adobe.marketing.mobile:edge:2.1.0
         project :app > com.adobe.marketing.mobile:edgeconsent:2.0.0
         project :app > com.adobe.marketing.mobile:edgeidentity:2.0.0
         project :app > com.adobe.marketing.mobile:optimize:2.0.0
         project :app > com.adobe.marketing.mobile:places:2.0.0
         project :app > com.adobe.marketing.mobile:userprofile:2.0.0
```

### Reproduce Scenario (including but not limited to)

Build an Android app with the following dependencies:

```
    "@adobe/react-native-aepassurance": "4.0.0",
    "@adobe/react-native-aepcore": "2.0.0",
    "@adobe/react-native-aepedge": "2.0.0",
    "@adobe/react-native-aepedgeconsent": "2.0.0",
    "@adobe/react-native-aepedgeidentity": "2.0.0",
    "@adobe/react-native-aepoptimize": "2.0.0",
    "@adobe/react-native-aepplaces": "2.0.0",
    "@adobe/react-native-aeptarget": "2.0.0",
    "@adobe/react-native-aepuserprofile": "2.0.0",
```

#### Steps to Reproduce

..

#### Platform and Version

Android

**Comment by praveek** [comment]
@kevindice Can you remove the snapshot repository from your app and only depend on artifacts from release repository? 
```
maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
```

**Comment by kevindice** [comment]
I'll try that as soon as I get back in front of my work laptop.  It looks like we had added it because it's what the sample app in this repo has:

https://github.com/adobe/aepsdk-react-native/blob/main/apps/AEPSampleApp/android/build.gradle#L51

![Screenshot_20230428-114254.png](https://user-images.githubusercontent.com/5779569/235217381-bea645fb-060c-483d-b3c3-b7db5b1d0300.png)

**Comment by cacheung** [comment]
Thanks for the info @kevindice.  We had that in the sample app for one of the beta React Native library.  We will remove it in the next update.

**Comment by kevindice** [comment]
Had a successful build 👍

Thanks for your help!

**Comment by cacheung** [comment]
@kevindice please let us know if this issue can be closed.

**Comment by kevindice** [comment]
Yes, I think so.  In general, I am weary of automatically receiving new versions of these packages.  We have a general requirement for deterministic builds, and this moving target situation is counter to that.  Is it possible for us to pin versions?

**Comment by cacheung** [comment]
Currently, we don't support setting the specific version for the Native SDKs other than taking the latest.

**Comment by kevindice** [comment]
That's frankly not something I'm comfortable with.  Builds should be deterministic.

**Comment by cacheung** [comment]
This would be a feature request.  Please Open a support ticket through this channel: https://experienceleague.adobe.com/?support-solution=General&support-tab=home#support for us to track.
