### ISSUE TITLE
What is the alternative for ACPAnalytics.sendQueuedHits() in AEP packages?

### ISSUE THREAD

**Issue by ShehanAmarakoon** [adobe/aepsdk-react-native#268]

**Comment by ShehanAmarakoon** [comment]
Thanks for the information.

I upgraded the ACP to AEP packages. But cannot see any hits on the AA dashboard for both iOS and Android.
All the IDs are correct and I can see the SDK initialize correctly.

ACP works fine with the same IDs.

// Previous Code
```
ACPCore.updateConfiguration({
      'analytics.server': ADOBE_ANALYTICS.SERVER,
      'analytics.rsids': ADOBE_ANALYTICS.RSIDS,
      'analytics.batchLimit': 10,
      'analytics.offlineEnabled': false,
    });
ACPAnalytics.sendQueuedHits();
```

// AEP Upgrade

```
MobileCore.updateConfiguration({
      'analytics.server': ADOBE_ANALYTICS.SERVER,
      'analytics.rsids': ADOBE_ANALYTICS.RSIDS,
      'analytics.batchLimit': 10,
      'analytics.offlineEnabled': false,
    });
  // ACPAnalytics.sendQueuedHits(); - no wrapper yet for AEP
```

Can you help me on this?

**Comment by cdhoffmann** [comment]
@ShehanAmarakoon Please refer to our migration guide here: https://github.com/adobe/aepsdk-react-native/blob/main/docs/migration.md

You can use the Edge Network path with Analytics.
