### ISSUE TITLE
React native getExperienceCloudId returns time out error.

### ISSUE THREAD

**Issue by bgrajesh57** [adobe/aepsdk-react-native#270]
getExperienceCloudId returning "time out error" form React native.

Adobe React native setup done based on the documentation. Please Let me know any library and configuration is missing.

React Native : 

```
"dependencies": {
    "@adobe/react-native-aepcore": "^2.0.0",
    "@adobe/react-native-aepedge": "^2.0.0",
    "@adobe/react-native-aepedgeidentity": "^2.0.0",
    "@adobe/react-native-aepedgeconsent": "^2.0.0",
}
```

iOS:

```
import AEPCore
import AEPSignal
import AEPServices
import AEPLifecycle
import AEPIdentity
import AEPAssurance
import AEPAnalytics
import AEPUserProfile


 MobileCore.setLogLevel(.debug)
     let adobeAppID = Bundle.main.object(forInfoDictionaryKey: "Adobe_D") as! String
     let appState = application.applicationState
     MobileCore.registerExtensions([ Assurance.self,
                                     Analytics.self,
                                     UserProfile.self,
                                     Signal.self,
                                     Lifecycle.self,
                                     Identity.self,
                                   ], {
       MobileCore.configureWith(appId: adobeAppID)
       if appState != .background { MobileCore.lifecycleStart(additionalContextData:
       ["contextDataKey": "contextDataVal"]) }
         })

```
Android:

````
import com.adobe.marketing.mobile.AdobeCallback;
import com.adobe.marketing.mobile.Analytics;
import com.adobe.marketing.mobile.Assurance;
import com.adobe.marketing.mobile.Identity;
import com.adobe.marketing.mobile.InvalidInitException;
import com.adobe.marketing.mobile.Lifecycle;
import com.adobe.marketing.mobile.LoggingMode;
import com.adobe.marketing.mobile.MobileCore;
import com.adobe.marketing.mobile.Signal;
import com.adobe.marketing.mobile.UserProfile;

 MobileCore.setApplication(this);
         MobileCore.setLogLevel(LoggingMode.DEBUG);
         try {
             Assurance.registerExtension();
             Analytics.registerExtension();
             UserProfile.registerExtension();
             Identity.registerExtension();
             Lifecycle.registerExtension();
             Signal.registerExtension();

             MobileCore.configureWithAppID(getString('adobe_ID'));
             MobileCore.start(new AdobeCallback() {
                 @Override
                 public void call(Object o) {
                     MobileCore.lifecycleStart(null);
                 }
             });
         } catch (InvalidInitException e) {

         }
````
### Expected Behaviour

getExperienceCloudId API should return value. 
```
import {Identity} from '@adobe/react-native-aepedgeidentity';

  Identity.getExperienceCloudId()
    .then(cloudId => console.log('experience Cloud id: ' + cloudId))
    .catch(error => console.log('experience cloud id Error: ' + error));
};

Ex: Expected value
52612667349873636375709475823783369529

```

### Actual Behaviour

getExperienceCloudId API should return value. 
```
import {Identity} from '@adobe/react-native-aepedgeidentity';

  Identity.getExperienceCloudId()
    .then(cloudId => console.log('experience Cloud id: ' + cloudId))
    .catch(error => console.log('experience cloud id Error: ' + error));
};

Error:
getExperienceCloudId call timed out
```

#### Steps to Reproduce

Call Identity.getExperienceCloudId()  function on react native App.

#### Platform and Version
iOS 
Android

#### Sample Code that illustrates the problem

````
import {Identity} from '@adobe/react-native-aepedgeidentity';

 Identity.getExperienceCloudId()
    .then(cloudId => console.log('experience Cloud id: ' + cloudId))
    .catch(error => console.log('experience cloud id Error: ' + error));
};
````

Looking forward to hear form you ASAP.
Thanks.

**Comment by cacheung** [comment]
@bgrajesh57 
In your react native code, you import the Identity library from @adobe/react-native-aepedgeidentity  ([Identity for Edge Network](https://developer.adobe.com/client-sdks/documentation/identity-for-edge-network/))

In your android and iOS native code, you registered with import com.adobe.marketing.mobile.Identity  (which is the [identity for Experience Cloud ID Service](https://developer.adobe.com/client-sdks/documentation/mobile-core/identity/)

They are two different identities libraries.

From your native code registration info, it seems like you are sending data to the solutions directly, not going through edge network.  In this case, in your react native, you need to remove import {Identity} from '@adobe/react-native-aepedgeidentity';

And
import {Identity} from '@adobe/react-native-aepcore';

Identity.getExperienceCloudId()
    .then(cloudId => console.log('experience Cloud id: ' + cloudId))
    .catch(error => console.log('experience cloud id Error: ' + error));
};

**Comment by bgrajesh57** [comment]
Thanks for the clarification 👍

**Comment by bgrajesh57** [comment]
@cacheung  We want to track analytics for the app. We want to use below methods.

```
MobileCore.trackState,
MobileCore.trackAction
```
In that we don't need for below dependency lib for React native? Please confirm , But in the documentation mentioned below lib required to install.

```
 "@adobe/react-native-aepedge": "^2.0.0",
 "@adobe/react-native-aepedgeidentity": "^2.0.0",
 "@adobe/react-native-aepedgeconsent": "^2.0.0",
```

**Comment by cacheung** [comment]
Which documentation you are referring to?
For using AEP-prefix mobile sdk and sending data to Analytics, please take a look of this [faq](https://developer.adobe.com/client-sdks/documentation/adobe-analytics/faq/#how-do-i-send-data-to-adobe-analytics-in-react-native-and-flutter).

In your native code, you have for Android
```
import com.adobe.marketing.mobile.Analytics;
Analytics.registerExtension();
```

How did you get the Analytics extension?

**Comment by bgrajesh57** [comment]
Hi @cacheung   Form Android  registered  import com.adobe.marketing.mobile.Analytics; and import com.adobe.marketing.mobile.MobileCore;

For you reference source below. 

````

import com.adobe.marketing.mobile.AdobeCallback;
import com.adobe.marketing.mobile.Analytics;
import com.adobe.marketing.mobile.Assurance;
import com.adobe.marketing.mobile.Identity;
import com.adobe.marketing.mobile.InvalidInitException;
import com.adobe.marketing.mobile.Lifecycle;
import com.adobe.marketing.mobile.LoggingMode;
import com.adobe.marketing.mobile.MobileCore;
import com.adobe.marketing.mobile.Signal;
import com.adobe.marketing.mobile.UserProfile;

 MobileCore.setApplication(this);
         MobileCore.setLogLevel(LoggingMode.DEBUG);
         try {
             Assurance.registerExtension();
             Analytics.registerExtension();
             UserProfile.registerExtension();
             Identity.registerExtension();
             Lifecycle.registerExtension();
             Signal.registerExtension();

             MobileCore.configureWithAppID(getString('adobe_ID'));
             MobileCore.start(new AdobeCallback() {
                 @Override
                 public void call(Object o) {
                     MobileCore.lifecycleStart(null);
                 }
             });
         } catch (InvalidInitException e) {

         }
````

From React native to get the ECID getting below error. Pease let me know anything we missed out.

````
import {Identity, MobileCore, PrivacyStatus} from '@adobe/react-native-aepcore';

 Identity.getExperienceCloudId()
    .then(cloudId => console.log('experience Cloud id: ' + cloudId))
    .catch(error => console.log('experience cloud id Error: ' + error));


Error: getExperienceCloudId returned an unexpected error: general.callback.timeout

````

**Comment by bgrajesh57** [comment]
@cacheung  I can see the experienceCloudId form Android as well :)

**Comment by addb** [comment]
Hi @bgrajesh57,

Can you attach the logs for this. Is there a pattern, is it happening more on app first launches? If the configuration and extensions are correctly installed. You will need to add retry mechanism to getECID API i.e. if you get timeout error you can retry calling the getECID API. Limit the number of retries based on the tolerance of the app. Before that still need to check if timeout is solely due to processing like downloading configuration to check for privacy status and then responding with ECID.

**Comment by cacheung** [comment]
@bgrajesh57 Have you got this issue resolved?

**Comment by bgrajesh57** [comment]
@cacheung  its resolved , thanks
