### ISSUE TITLE
How can I setup cusPreferredLanguage

### ISSUE THREAD

**Issue by inpendio** [adobe/aepsdk-react-native#292]
Hi,

so we have a situation where we need to set language for the subscriber. In the same table where we can find cloid ID, registration token, etc., there is a field Language (cusPreferredLanguage). How to set this field from react-native programmatically (and update it if language changes)?

**Comment by yangyansong-adbe** [comment]
Hi @inpendio , I can't understand your question. Can you provide further information on how you use our React Native SDK within your project? And, which SDK extension/package is causing the language issue?

**Comment by inpendio** [comment]
Nothing is causing the language issue. I just want to set up the preferred language for the user. 
The integration is basic, we followed the docs. Registration token and cloud ID are created automatically. But we want to set a preferred language for the user (subscriber), so that we can send notifications in the correct form. 

![Screenshot 2023-09-28 at 17 26 40](https://github.com/adobe/aepsdk-react-native/assets/44359614/e5b8429d-2440-49ab-aaa4-acf5afc4443a)

**Comment by yangyansong-adbe** [comment]
Oh, I see. Which Adobe solution UI are you referring to? I can forward your question to the solution expert.

**Comment by inpendio** [comment]
This one, AEP.
We had some support, but even they didn't know. I thought maybe developers know...

**Comment by yangyansong-adbe** [comment]
Hi @swarna04, this question seems to be related to a campaign. Can you help to provide some suggestions? 

cc @dsoffiantini

**Comment by swarna04** [comment]
@inpendio You can set up a launch rule with `Send PII` action (post body as shown below):
```
{
"marketingCloudId":
"{%%mcid%%}",
"cusPreferredLanguage":
"{%contextdata.preferredLanguage%}" 
}
```
For details, see https://experienceleague.adobe.com/docs/campaign-standard/using/administrating/configuring-mobile/configuring-rules-launch.html?lang=en#pii-postback. In the app, invoke Mobile Core's `collectPii` API and pass the desired `preferredLanguage` value in the dictionary.

```
MobileCore.collectPii({preferredLanguage: '<preferred-language>'});
```
Hope this helps! Please let us know if you run into any issues. Thanks.

**Comment by swarna04** [comment]
@inpendio Thanks for your reply. Not sure I understand when you say that `MobileCore.collectPii` doesn't work! Do you not see the request made to ACS server with the configured post body? Have you verified the rule is configured as per the docs and published to the environment from where you select the environment file ID for your app? Do you have SDK logs to share (probably redacted) so that we can investigate this further? Please let us know. Thanks.

**Comment by cacheung** [comment]
@inpendio You can get the SDK logs from the native IDEs Debug Windows.

1. Use MobileCore.setLogLevel and set the level to VERBOSE/TRACE, and call this API before any other SDK API call, even before extensions registration. See sample code [here](https://developer.adobe.com/client-sdks/documentation/mobile-core/api-reference/#setloglevel).

2.
iOS: In Xcode dev console (View → Show Debug Area)
Android: Android Studio >  logcat windows

Run the test steps and copy all the content in the log window to a text file and share with us.

**Comment by cacheung** [comment]
Closing the issue due to low activity.  Please open a new issue if you have any other questions.

**Comment by inpendio** [comment]
Hi. Well, I don't know if you manage to solve it. We currently use Pii URL for this. And we don't have much time to debug it.
