### ISSUE TITLE
Issues Imports/AppDelegate file

### ISSUE THREAD

**Issue by adam-padden** [adobe/aepsdk-react-native#293]
Hello,

I am currently attempting to implement the AEP SDK into a React Native project. 

React Native: v69.1
Xcode: v15.0

The issue I am running into is during the initialization process with iOS.  I am receiving the following error messages inside my AppDelegate.h file while using the code snippets provided in the documentation.  

**AppDelegate.h**
![image](https://github.com/adobe/aepsdk-react-native/assets/106393931/e46c2daa-c7bd-4efa-b729-0bc10dc9e57d)

I was also wondering if the code snippet provided for the AppDelegate.m file would also work in RN's new architecture that utilizes the .mm format instead. 

Any help would be greatly appreciated!  :)

Thanks,
Adam

**Comment by yangyansong-adbe** [comment]
Hi @adam-padden, this looks like a duplicated issue. Please take a look at this issue https://github.com/adobe/aepsdk-react-native/issues/247 and try the solution mentioned in the comments.

**Comment by adam-padden** [comment]
@yangyansong-adbe - Thank you for this, I'm not sure how I missed it.  It seems to be working now.
