### ISSUE TITLE
ACP to AEP ReactNative Migration failling

### ISSUE THREAD

**Issue by ArlemGabriel** [adobe/aepsdk-react-native#297]
### Expected Behaviour
I've been trying to migrate ACP-Prefix to AEP-Prefix using the migration guide https://github.com/adobe/aepsdk-react-native/blob/main/docs/migration.md . The expected behavior after making the migration is TrackState and TrackAction sending data to Adobe and data reaching to Adobe.

### Actual Behaviour
Data isn't being sent and isn't reaching to Adobe when using trackState and trackAction. 

#### Steps to Reproduce
REACT NATIVE DEPENDENCIES

    "@adobe/react-native-aepcore": "^5.0.1"

APPDELEGATE REGISTRATION

@import AEPCore;
@import AEPServices;
@import AEPLifecycle;
@import AEPIdentity;
@import AEPSignal;

[AEPMobileCore configureWithAppId:ADB_APP_ENVIRONMENT_ID];
    [AEPMobileCore setLogLevel: AEPLogLevelTrace];
    
    //[ACPCore setWrapperType:ACPMobileWrapperTypeReactNative];
    const UIApplicationState appState = application.applicationState;
    
    [AEPMobileCore registerExtensions: @[
            AEPMobileIdentity.class,
            AEPMobileLifecycle.class,
            AEPMobileSignal.class,
        ] completion:^{
          if (appState != UIApplicationStateBackground) {
           [AEPMobileCore lifecycleStart:nil];
          }
        }];

TRACK STATE AND TRACK ACTION USAGE

import {MobileCore} from '@adobe/react-native-aepcore';

let contextData: { [key: string]: string } = {
		"event.name": "Page Loaded Test1",
		"page.name": "login",
	}
	useEffect(() => {
		MobileCore.trackState('login', contextData);
	}, []);

LAUNCH PROPERTY EXTENSIONS
Adobe Analytics v2.3.4
Mobile Core v2.2.3
Profile v2.1.2
Identity v1.1.2

#### Platform and Version
"react-native": "0.71.6",

#### More Details
There are two ways to implement Adobe Analytics for Mobile (https://developer.adobe.com/client-sdks/home/getting-started/#integration-via-solutions-specific-endpoints)
1.  Specific endpoints
2. AEP and datastreams.

Is there a way to implement Adobe Analytics in ReactNative using Point Product Implementation? or unfortunately this is just available for native iOS and Android ?

**Comment by cacheung** [comment]
AEP React Native only supports sending Analytics data through Edge Network. It doesn't support Analytics Extension for sending data to Analytics endpoint directly.

For migrating ACP react native trackAction/trackState implementation, they are supported  through [Edge Bridge](https://github.com/adobe/aepsdk-react-native/tree/main/packages/edgebridge) and [Edge Network](https://github.com/adobe/aepsdk-react-native/tree/main/packages/edge) extensions. 
https://github.com/adobe/aepsdk-react-native/tree/main/packages/core#trackaction

More info can be found in this [migration doc](https://developer.adobe.com/client-sdks/solution/adobe-analytics/migrate-to-edge-network/).

**Comment by ArlemGabriel** [comment]
Thanks for clearing that up @cacheung ! Adding that info in the documentation for AEP migration in ReactNative will be super helpful since there is a lot of people who doesn't know that sending data to Analytics endpoint isn't supported anymore.

**Comment by cacheung** [comment]
The migration info is listed in the note session under this table:
https://github.com/adobe/aepsdk-react-native/blob/main/docs/migration.md#switch-dependent-packages
