### ISSUE TITLE
Xcode 15 failed to verify module interface of AEPRulesEngine; textual interface may be broken

### ISSUE THREAD

**Issue by moribaleta** [adobe/aepsdk-react-native#308]
building the app on Xcode 15 
fails to build due to an error message
![Screenshot 2023-12-04 at 3 27 11 PM](https://github.com/adobe/aepsdk-react-native/assets/13190143/82905e12-c068-497e-a37f-1dd2837ab198)

using AEP 5.0.1/5.0.0

### Expected Behaviour
being able to build the project successfully

### Actual Behaviour
error showing on build on all AEP pods

#### Steps to Reproduce
build on XCode 15

#### Platform and Version
XCode 15.0.1

**Comment by cacheung** [comment]
Please refer to this thread.
https://github.com/adobe/aepsdk-react-native/issues/263

**Comment by moribaleta** [comment]
thank you
