### ISSUE TITLE
[Request] Add support for NativeScript - aepsdk-nativescript

### ISSUE THREAD

**Issue by fpaaske** [adobe/aepsdk-react-native#310]
I'm not sure where this request fit best, but since NativeScript is similar to React Native (cross platform app development framework) I thought this could be a nice place to ask.

Would it be possible for you to provide an official SDK for NativeScript? I don't mean to add support for it in this repository, but the create a new repo for this purpose. There is an existing one [here](https://github.com/Essent/nativescript-adobe-marketing-cloud), but it's now a bit dated, and I don't think they (Essent) are so active in the mobile app world anymore.

More info on NativeScript: https://nativescript.org/
Plugin seed for NativeScript plugins: https://github.com/NativeScript/plugin-seed

**Comment by Mr-Ice-Adobe** [comment]
Hi @fpaaske, I'm the PM here at Adobe or the AEP Mobile SDKs. Right now, we don't have any plans to build an official SDK for NativeScript, but I've noted your request and I'll take it into consideration in the future when making decisions about cross-platform app development frameworks. 

The AEP Mobile SDKs are open source, this will enable you to write your own NativeScript wrapper if you wish.

**Comment by cacheung** [comment]
Closing the ticket since there is no action task.  
We can still make comments while the ticket is closed.
