### ISSUE TITLE
IOS build fails: underlying Objective-C module 'AEPServices' not found

### ISSUE THREAD

**Issue by Vrapce-gif** [adobe/aepsdk-react-native#317]
Hello,
I see IOS build error showing this:

- underlying Objective-C module 'AEPServices' not found.
- /Users/expo/workingdir/build/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AEPServices.build/Objects-normal/x86_64/AEPServices.private.swiftinterface:5:19
- // swift-interface-format-version: 1.0
    | ^ failed to verify module interface of 'AEPServices' due to the errors above; the textual interface may be broken by project 
     issues or a compiler bug

**Comment by cacheung** [comment]
@Vrapce-gif 
I saw the similar question from Experience League.
Adding below in the pod file should resolve the issue.

```
post_install do |installer|
  installer.pods_project.targets.each do |t|
    if t.name.start_with?("AEP")
      t.build_configurations.each do |bc|
          bc.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -no-verify-emitted-module-interface'
      end
    end
  end
end
```

https://github.com/adobe/aepsdk-react-native/issues/263#issuecomment-1498393770
