### ISSUE TITLE
[Edge Bridge - Android] Test to verify new data format is being used after updating to version to Android v3.0.0

### ISSUE THREAD

**Issue by kevinlind** [adobe/aepsdk-react-native#327]
### Task Description
After updating Edge Bridge extension to next major Android version 3.0.0, run test app on Android to verify the new data format is being used when sending requests to the Adobe Edge Network.

See internal wiki "Edge Bridge to Analytics data conversion" for new data mapping format.
See Epic MOB-20404

**Comment by cacheung** [comment]
Tested on react-native-aepedgebridge@6.0.0, the new data format is being used.
