### ISSUE TITLE
Support for react native >= 0.73.x

### ISSUE THREAD

**Issue by thoughtworks-tcaceres** [adobe/aepsdk-react-native#329]
### Expected Behaviour
supports react native 0.73.x

### Actual Behaviour
does not support react native 0.73.x

#### Platform and Version
React native >= 0.73.x

According to the readme's doc this package `Requires React Native (0.60.0 - 0.72.x)`. 
Is there any plan on support >= 0.73.x

Thanks in advance.

**Comment by yangyansong-adbe** [comment]
@thoughtworks-tcaceres Could you log a [customer ticket](https://experienceleague.adobe.com/home?support-tab=home#support) for the issue so that we can review it within the team?

**Comment by thoughtworks-tcaceres** [comment]
> @thoughtworks-tcaceres Could you log a [customer ticket](https://experienceleague.adobe.com/home?support-tab=home#support) for the issue so that we can review it within the team?

Looks like there is currently a bug with submitting tickets, it does nothing when clicking on the 'open ticket' button.
Will try in a bit. Thank you. 🙏

**Comment by thoughtworks-tcaceres** [comment]
> @thoughtworks-tcaceres Could you log a [customer ticket](https://experienceleague.adobe.com/home?support-tab=home#support) for the issue so that we can review it within the team?

Unfortunately looks like I am still unable to log a customer ticket from the site. 😅

**Comment by yangyansong-adbe** [comment]
@thoughtworks-tcaceres, I'm sorry to hear that. I suggest that you contact the Adobe consultant team directly. Also, could you kindly provide the customer's name here, if that is alright with you?

**Comment by yangyansong-adbe** [comment]
@thoughtworks-tcaceres did you manage to log a customer ticket or contact the Adobe consultant team? Regarding the 0.73 support, it is currently on our backlog, but we don't have an ETA for its release at this time. We will be providing additional information further down this page once we have a dedicated date.

**Comment by thoughtworks-tcaceres** [comment]
@yangyansong-adbe , I was able to speak to someone directly, thank you. 🙏

**Comment by ahmyr** [comment]
@thoughtworks-tcaceres, we have added namespace support required for React Native 0.73:
https://developer.adobe.com/client-sdks/home/release-notes/#april-24-2024

Support for the new React Native architecture is still to come.
