### ISSUE TITLE
Support for React Native Version 0.73.X and above

### ISSUE THREAD

**Issue by ram-vilash** [adobe/aepsdk-react-native#340]
When we will get the support for React Native Version 0.73.X + ?

**Comment by thoughtworks-tcaceres** [comment]
According to [this recent message](https://github.com/adobe/aepsdk-react-native/issues/329#issuecomment-2045685016), it's on their backlog but no ETA as of yet.

**Comment by yangyansong-adbe** [comment]
Hi @ram-vilash,  @thoughtworks-tcaceres 
Our React Native libraries, version 6.0.1, have been released to support version 0.73.x of React Native. Please try it out. I will close this issue, please feel free to reopen or create a new one if you have other questions.

**Comment by thoughtworks-tcaceres** [comment]
> Hi @ram-vilash, @thoughtworks-tcaceres Our React Native libraries, version 6.0.1, have been released to support version 0.73.x of React Native. Please try it out. I will close this issue, please feel free to reopen or create a new one if you have other questions.

Thanks @yangyansong-adbe , this is great news.
In case it was missed, I think this [link](https://developer.adobe.com/client-sdks/home/current-sdk-versions/#react-native) should be updated to specific 0.73.x instead of 0.72.x now. 👍

**Comment by yangyansong-adbe** [comment]
@thoughtworks-tcaceres  Thank you for mentioning that. Actually, the PR was merged. https://github.com/AdobeDocs/aep-mobile-sdkdocs/pull/587/files We plan to deploy it by the end of today.
