### ISSUE TITLE
Compile Issue with npm run tsc

### ISSUE THREAD

**Issue by steven326** [adobe/aepsdk-react-native#353]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-react-native/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

Typescript compile issue on files - 
@adobe/react-native-aepedge/ts/Edge.ts
@adobe/react-native-aepedge/ts/models/ExperienceEvent.ts

### Environment

OS: macOS 14.4.1
CPU: (8) x64 Apple M1 Pro
Memory: 34.47 MB / 32.00 GB

### Steps to reproduce

1. npm install @adobe/react-native-aepedge
2. npm run tsc

### Current behavior

node_modules/@adobe/react-native-apedge/ts/Edge.ts(70,3): error TS2322: Type ' (hint?: string l undefined) => void' is not
assignable to type'(hint?:string | null | undefined) → void'.
Types of parameters 'hint' and 'hint' are incompatible.
Type 'string I null | undefined' is not assignable to type 'string I undefined'. node_modules/@adobe/react-native-apedge/ts/models/ExperienceEvent.ts(54,7): error TS2322: Type
«string, any> I unc
'Record«string, any> | null | undefined' is not assignable to type 'Record«string, any> | undefi ned'•
Type 'null' is not assignable to type 'Record«string, any> | undefined'.
node_modules/@adobe/react-native-apedge/ts/models/ExperienceEvent.ts (55,7): error TS2322: Type
'string
I null I undefined' is not assignable to type 'string I undefined".
Type 'null' is not assignable to type
'string I undefined'.
node_modules/@adobe/react-native-apedge/ts/models/ExperienceEvent.ts (56,7): error TS2322: Type
'string I null | undefined' is not
assignable to type 'string I undefined'.
anne vender 56.2 error T52372: Te
node_ modules/@adobe/react-native-apedge/ts/models/ExperienceEvent. ts (57,7): error TS2322: Type
"Record«string, any> | null | undefined' is not assignable to type Record«string, any> | undefi ned'.
node_modules/@adobe/react-native-apedge/ts/models/ExperienceEvent. ts(60,7): error TS2322: Type
'Record«string, any> | null | undefined' is not assignable to type 'Record<string, any> | undefi ned'.
node_modules/@adobe/react-native-apedge/ts/models/ExperienceEvent. ts (61,7): error TS2322: Type
'string I null | undefined' is not
assignable to type
'string I undefined'.
npm ERR! Lifecycle script 'compile' failed with error: npm ERR! Error: command

**Comment by alanblins** [comment]
The package.json files of all libraries such as `@adobe/react-native-apedge` contains:
```
"main": "./ts/index.ts"
```
It means when you import the library into your project it will try to recompile as well. 
If your tsconfig is different of `adobe/aepsdk-react-native`'s tsconfig, then what compiles without issues on `adobe/aepsdk-react-native` could cause errors on your side. If your project has the option `strickNullCheck:true` while the adobe has `strickNullCheck:false` the typescript won't work for you.
I believe there are two possible options:
* Update your tsconfig by adding `strickNullCheck:false`
* Wait for the `adobe/aepsdk-react-native` library fixes the issue related to declaration files. I raised a [PR](https://github.com/adobe/aepsdk-react-native/pull/354) to fix that.

**Comment by yangyansong-adbe** [comment]
@steven326, I will close this page since the issue has been addressed in version 6.0.2. You can find release notes [here](https://developer.adobe.com/client-sdks/home/release-notes/#june-6-2024).  Let us know if you have other questions. 
@alanblins  thank you for the contribution.
