### ISSUE TITLE
Adobe integration conflicts with firebase which require use_frameworks! :linkage => :static

### ISSUE THREAD

**Issue by kopposh** [adobe/aepsdk-react-native#391]
## Prerequisites

- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-analytics-android/security/policy).

**Bug summary:**
Hi guys, I'm trying to integrate AEP SDK into bare react native app. I have followed the guidelines too. The integration works fine if I do it without firebase but if I try to integrate adobe after firebase, receiving the below error

<img width="1181" alt="Screenshot 2024-10-25 at 4 53 33 PM" src="https://github.com/user-attachments/assets/e1df936a-63c8-43c1-a2fd-1c76c72ff93a">

This is happening for bare react native app and also in react native expo app.

**Environment**
Operating System: iOS 18.0. (simulator: iPhone 16, Device: iphone 15)
React native version: 0.74.5
Xcode version: 16.0
Adobe packages:
"@adobe/react-native-aepassurance": "6.0.2",
    "@adobe/react-native-aepcore": "6.0.2",
    "@adobe/react-native-aepedge": "6.0.2",
    "@adobe/react-native-aepedgebridge": "6.0.2",
    "@adobe/react-native-aepedgeconsent": "6.0.2",
    "@adobe/react-native-aepedgeidentity": "6.0.2",
    "@adobe/react-native-aepplaces": "6.0.2",
    "@adobe/react-native-aeptarget": "6.0.2",
    "@adobe/react-native-aepuserprofile": "6.0.2",
    "@react-native-firebase/app": "20.3.0",
    "@react-native-firebase/messaging": "20.3.0",

**Steps to reproduce**
Create a new React Native project.
Install the dependencies mentioned above and follow the guidelines for each of the packages
Run the iOS app. 

**Current behaviour**
Adobe integration in not working with react-native-firebase. or with static frameworks (use_frameworks! :linkage => :static) 

**Expected behaviour**
Adobe integration should work along with firebase which require setting static frameworks either in a bare react native app or react native expo app

**Comment by cacheung** [comment]
@kopposh The Adobe `aepsdk-react-native` currently supports only the dynamic linking framework.

**Comment by kopposh** [comment]
@cacheung does this mean I cannot integrate firebase along with adobe? or Can i specify something like this below to set adobe dependencies as dynamic and firebase as static? please suggest an alternative to use both the packages together.

``
# Use dynamic frameworks for Adobe dependencies
  use_frameworks! :linkage => :dynamic

  pod 'react-native-aepassurance', :path => '../node_modules/@adobe/react-native-aepassurance'
  pod 'react-native-aepcore', :path => '../node_modules/@adobe/react-native-aepcore'
  pod 'react-native-aepedge', :path => '../node_modules/@adobe/react-native-aepedge'
  pod 'react-native-aepedgebridge', :path => '../node_modules/@adobe/react-native-aepedgebridge'
  pod 'react-native-aepedgeconsent', :path => '../node_modules/@adobe/react-native-aepedgeconsent'
  pod 'react-native-aepedgeidentity', :path => '../node_modules/@adobe/react-native-aepedgeidentity'
  pod 'react-native-aepplaces', :path => '../node_modules/@adobe/react-native-aepplaces'
  pod 'react-native-aeptarget', :path => '../node_modules/@adobe/react-native-aeptarget'
  pod 'react-native-aepuserprofile', :path => '../node_modules/@adobe/react-native-aepuserprofile'

  # Use static frameworks for react-native-firebase dependencies
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app', :linkage => :static
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging', :linkage => :static

  # Other pods
``

**Comment by cacheung** [comment]
@kopposh We haven't had chance to test that, so we're not sure about the solution.  It might be worth giving it a try and see if it works.

**Comment by casmj** [comment]
Hi @kopposh, one other thing you could try is to enable modular headers for Firebase dependencies. It looks like this can sometimes resolve issues with static and dynamic framework conflicts:
```
pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app', :modular_headers => true
pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging', :modular_headers => true
```
By using modular headers for Firebase, we can treat them as dynamic frameworks, which might allow them to coexist with dynamically-linked frameworks like ours.

This is untested, but worth a try.

**Comment by kopposh** [comment]
@casmj Thank you for the hinting that we can try modular headers for Firebase . We are able to progress with the integration by removing use_frameworks! :linkage => :static and only adding necessary pod changes as below. I can confirm once we move to prod without any build related issue. Thank you

```
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
```

**Comment by casmj** [comment]
Nice!! 'Glad you're able to keep moving past this issue now. Please let us know how else we can help. And thanks for letting us know that this worked; your feedback helps us curate our FAQs and other documentation.

**Comment by casmj** [comment]
Hi @kopposh , at this point we're going to close this issue unless you had any other related questions.
