### ISSUE TITLE
Android build cannot be assembled, because "adobe_react-native-aepcore" package throws 403 error

### ISSUE THREAD

**Issue by oleksandr-dziuban** [adobe/aepsdk-react-native#407]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-react-native/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

Android build fails with error:

```
Could not determine the dependencies of task ':adobe_react-native-aepcore:verifyReleaseResources'.
> Could not resolve all task dependencies for configuration ':adobe_react-native-aepcore:releaseRuntimeClasspath'.
   > Could not resolve com.adobe.marketing.mobile:core:3.+.
     Required by:
         project :adobe_react-native-aepcore
      > Failed to list versions for com.adobe.marketing.mobile:core.
         > Unable to load Maven meta-data from https://s3-us-west-2.amazonaws.com/si-mobile-sdks/android/com/adobe/marketing/mobile/core/maven-metadata.xml.
            > Could not GET 'https://s3-us-west-2.amazonaws.com/si-mobile-sdks/android/com/adobe/marketing/mobile/core/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for com.adobe.marketing.mobile:core.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/core/maven-metadata.xml.
            > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/core/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out
```

Both resources are not available and throw 403 / 504 errors:

https://s3-us-west-2.amazonaws.com/si-mobile-sdks/android/com/adobe/marketing/mobile/core/maven-metadata.xml
https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/core/maven-metadata.xml

### Environment

```
System:
  OS: macOS 15.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 111.59 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2023.03.13.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/<user>/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/<user>/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
```

### Steps to reproduce

1. Install both packages according to documentation:
```
    "@adobe/react-native-aepcore": "6.0.1",
    "@adobe/react-native-aeptarget": "6.0.1",
```

2. Run Android release build assembling

### Current behavior

Android build cannot be assembled

### Expected behavior

Android build assembled succesfully

**Comment by ayoubechc** [comment]
I face the same issue

**Comment by BasicHealin** [comment]
<img width="978" alt="Screenshot 2024-12-11 at 12 30 12" src="https://github.com/user-attachments/assets/c1981003-4dfd-4433-9f1a-612b9e34794f">

**Comment by snanthagopal** [comment]
Same issue for me as well 

Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/edgeidentity/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out

**Comment by VadimRydenko** [comment]
I have the same issue

**Comment by oleksandr-dziuban** [comment]
Yeah, seems like a global issue. Not related to local networking, or VPNs or something else

**Comment by tberchanov** [comment]
The same issue is on my side.

However, the library from maven repository is downloadable.
https://mvnrepository.com/artifact/com.adobe.marketing.mobile/core/3.2.0
https://repo1.maven.org/maven2/com/adobe/marketing/mobile/core/3.2.0/

**Comment by cacheung** [comment]
Closing the ticket.  Please raise it again, if it still happens to you.
