### ISSUE TITLE
Add async error handling in native code

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/aepsdk-react-native#52]
### Expected Behaviour
For async API calls, the native SDKs have provided the AdobeCallbackWithError (Android) and the Error (iOS) classes to get error notification for operation timeout or other internal errors. Update React Native Android/iOS implementation code to handle internal errors.
https://aep-sdks.gitbook.io/docs/foundation-extensions/mobile-core/mobile-core-api-reference#adobecallbackwitherror

https://github.com/adobe/aepsdk-core-ios/blob/ee0aff1670b4ef283f62b1ee993e8bf611f31b6b/AEPCore/Sources/core/MobileCore%2BConfiguration.swift#L79

**Comment by emdobrin** [comment]
We should review this for iOS implementation too. Feel free to update description to include both or create a separate task for it.

**Comment by yangyansong-adbe** [comment]
@emdobrin the code change (https://github.com/adobe/aepsdk-react-native/pull/86) has been merged to the staging branch, let me know if I can close this issue.
